version: "3"
services:
    mongodb:
      hostname: mongodb
      image: mongo:4.4.2
      ports:
        - "27018:27017"

    prometheus:
      image: prom/prometheus:v2.1.0
      volumes:
        - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
      command:
        - '--config.file=/etc/prometheus/prometheus.yaml'
      ports:
        - '9090:9090'

    grafana:
      image: grafana/grafana
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=pass
      depends_on:
        - prometheus
      ports:
        - '3000:3000'

    django:
        container_name: books
        build: 
          context: ../
          dockerfile: Dockerfile
        volumes:
          - "../:/usr/src/app"

        command: supervisord -n
        ports:
            - "8700:8700"
        sysctls:
            - net.core.somaxconn=65535

    nginx:
      image: nginx:1.19.5-alpine
      depends_on:
        - django
      ports:
        - "80:80" 
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/sites-enabled/nginx.conf
        - ./nginx/site_enabled/default.conf:/etc/nginx/conf.d/default.conf
      logging:
          driver: syslog
          options:
            tag: nginx
            syslog-address: "tcp://logstash:5000"
      restart: always
